categories:
  - id: system
    name: システム
  - id: manufacturing
    name: 製造
  - id: security
    name: セキュリティ
  - id: ai
    name: AI
  - id: dev
    name: 開発

sources:
  # --- システム ---
  - id: aws-blog
    name: AWS Blog
    category: system
    url: https://aws.amazon.com/blogs/aws/feed/

  - id: gcp-blog
    name: Google Cloud Blog
    category: system
    url: https://cloud.google.com/blog/rss

  # --- セキュリティ ---
  - id: cisa-all
    name: CISA Cybersecurity Advisories
    category: security
    url: https://www.cisa.gov/cybersecurity-advisories/all.xml

  - id: jpcert
    name: JPCERT/CC
    category: security
    url: https://www.jpcert.or.jp/rss/jpcert-all.rdf

  # --- AI (Foundations / Models) ---
  - id: openai-blog
    name: OpenAI Blog
    category: ai
    url: https://openai.com/blog/rss/
    
  - id: openai-news
    name: OpenAI News
    category: ai
    url: https://openai.com/news/rss.xml

  - id: google-ai-blog
    name: Google AI Blog
    category: ai
    url: https://ai.googleblog.com/feeds/posts/default

  - id: deepmind-blog
    name: Google DeepMind Blog
    category: ai
    url: https://deepmind.google/blog/rss.xml

  - id: meta-ai
    name: Meta AI Blog
    category: ai
    url: https://ai.facebook.com/blog/rss/

  - id: microsoft-ai
    name: Microsoft AI Blog
    category: ai
    url: https://blogs.microsoft.com/ai/feed/

  - id: aws-ml
    name: AWS Machine Learning Blog
    category: ai
    url: https://aws.amazon.com/blogs/machine-learning/feed/

  - id: huggingface-blog
    name: Hugging Face Blog
    category: ai
    url: https://huggingface.co/blog/feed.xml
      # --- AI (Research / OSS) ---
  - id: arxiv-ai
    name: arXiv AI (cs.AI)
    category: ai
    url: http://export.arxiv.org/rss/cs.AI

  - id: arxiv-ml
    name: arXiv Machine Learning
    category: ai
    url: http://export.arxiv.org/rss/cs.LG

  # --- 製造 (OT/ICS) ---
  - id: mhi
    name: Mitsubishi Heavy Industries News
    category: manufacturing
    url: https://www.mhi.com/rss/mhi_news.xml

  - id: siemens-cert
    name: Siemens ProductCERT Advisories
    category: manufacturing
    url: https://www.siemens.com/cert/rss/advisories.xml

  # --- 開発 ---
  - id: github-blog
    name: GitHub Blog
    category: dev
    url: https://github.blog/feed/

  - id: microsoft-devblogs
    name: Microsoft DevBlogs
    category: dev
    url: https://devblogs.microsoft.com/feed/
